### ISSUE TITLE
Customize map marker icon using url specified in JSON

### ISSUE THREAD

**Issue by anarosner** [anarosner/storymap-shortlist-case-studies#1]
I have been able to manually edit the JSON and set up code to pull it into to the js application. i.e. the line
`app.data.getWebAppData().getCustomIconURL()`
works. But, it appears that the point in code in which the icons are rendered, in the file 
'src/app/storymaps/tpl/core/MainView.js' (around line 135), that data isn’t yet available (according to a line I put in to log the values to the console). 

Once the application is loaded, if I run the above line in the console it returns the correct value. 

I've put in some console logs to try to deteremine at what point the web app data is available.

**Comment by elliothimmelfarb** [comment]
I have to say that I am really stumped on this one, not to mention that this is the most poorly composed application I've looked at. But anyways, here is what I can gather about this issue:

My number one confusion is that I could not figure out how `app.data.getWebAppData().getCustomIconURL()` ever returns the value we want from the console (after the full load) because I cannot find a case where `app.data.getWebAppData().setCustomIconURL()` fires with a non-null value being passed in. There are two places where it gets run: 'src/app/storymaps/tpl/core/MainView.js' around lines 1623 and 1662, but placing console logs next to them does not log, meaning that these lines are not being run. I can't find where the `customIconURL` is being set but finding that will tell us the point after which we will have the value and can set _icon.src with it. 

The other thing I was having difficulty finding, is where `app.data.setResponse(response)` actually fires with a valid response. I searched the whole project and attempted to log `response` in each place where `app.data.setResponse(response)` appears those pieces of code weren't firing or the `response` value was not valid. If we are trying to call `.setCustomIconURL()` with passing in the value of `.getResponse()` we need to find where `setResponse()` is firing with a valid `response`.

It might be my unfamiliarity with Dojo, but I'm finding it strange that I am not able to find where these class properties are actually being set. It really should not be that difficult, unless they are being set by circumventing the the setters, but I did search for that and didn't come up with anything.

Apologies for not being able to help more on this issue, but I am really stumped here. I am hoping that what I shared above is enough to help you keep going or pivot to another solution. Let me know if there is anything more I can do.

**Comment by elliothimmelfarb** [comment]
We found a spot further down in the file where the desired data from the JSON response was available. We discovered that `_icon` was a global variable and therefore available in the entire file so we were able to set the custom url attribute on the `_icon` object much later in the file.
